### ISSUE TITLE
400 response from server could be handled more gracefully

### ISSUE THREAD

**Issue by philipowen** [CiscoDevNet/ciscosparkapi#21]
If receiving a 400 response when posting a message, the following Traceback is generated:

Traceback (most recent call last):
  File "/etc/icinga2/scripts/spark-host-notification.py", line 18, in <module>
    message = api.messages.create(room_id, text=message_text)
  File "/var/spool/icinga2/.local/lib/python2.6/site-packages/ciscosparkapi/api/messages.py", line 282, in create
    json_obj = self.session.post('messages', json=post_data)
  File "/var/spool/icinga2/.local/lib/python2.6/site-packages/ciscosparkapi/restsession.py", line 188, in post
    check_response_code(response, erc)
  File "/var/spool/icinga2/.local/lib/python2.6/site-packages/ciscosparkapi/helper.py", line 104, in check_response_code
    response=response)
  File "/var/spool/icinga2/.local/lib/python2.6/site-packages/ciscosparkapi/exceptions.py", line 49, in __init__
    response_text)
ValueError: zero length field name in format

**Comment by philipowen** [comment]
Suspect this is actually a Python version issue. This happened using 2.6

**Comment by cmlccie** [comment]
Thank you for reporting this @philipowen .  Getting the unit tests and tox setup for this package should help us more consistently verify version compatibility.
