### ISSUE TITLE
Unprintable SparkApiError

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/ciscosparkapi#46]
Something is broken in `ciscosparkapi.exceptions.SparkApiError.__str__()`

``` python
>>> spark.memberships.create(room.id, personId=me.id)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/api/memberships.py", line 219, in create
    json_obj = self._session.post('memberships', json=post_data)
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/restsession.py", line 425, in post
    **kwargs)
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/restsession.py", line 276, in request
    check_response_code(response, erc)
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/utils.py", line 106, in check_response_code
    raise SparkApiError(response)
ciscosparkapi.exceptions.SparkApiError: <unprintable SparkApiError object>
```

**Comment by cmlccie** [comment]
I simplified and refactored the structure of the package exceptions, and enhanced the `SparkApiError` exception to include the formatted details of the request and response associated with the error.

``` python
import ciscosparkapi
spark = ciscosparkapi.CiscoSparkAPI()
rooms = spark.rooms.list(type='group', max=1)
i = iter(rooms)
room = next(i)
me = spark.people.me()
spark.memberships.create(room.id, personId=me.id)
Traceback (most recent call last):
  File "<input>", line 7, in <module>
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/api/memberships.py", line 219, in create
    json_obj = self._session.post('memberships', json=post_data)
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/restsession.py", line 425, in post
    **kwargs)
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/restsession.py", line 276, in request
    check_response_code(response, erc)
  File "/Users/chrlunsf/dev/projects/ciscosparkapi/ciscosparkapi/utils.py", line 137, in check_response_code
    raise SparkApiError(response)
ciscosparkapi.exceptions.SparkApiError: Response Code [409] - The request could not be processed because it conflicts with some established rule of the system. For example, a person may not be added to a room more than once.
------------------------------------Request------------------------------------
POST https://api.ciscospark.com/v1/memberships
User-Agent: python-requests/2.18.3
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer <omitted>
Content-type: application/json;charset=utf-8
Content-Length: 207
{"roomId":
"Y2lzY29zcGFyazovL3VzL1JPT00vMjdjNTFjNjAtYTk5NS0xMWU3LWJjNDctMjE1YTFkZjk5MGJh",
"personId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9mZjhlZTZmYi1hZmVmLTRhNGQtOTJiMS1kNm
IyMTZiNTg5NDk", "isModerator": false}
-----------------------------------Response------------------------------------
409 Conflict
Content-Length: 219
Content-Type: application/json
Date: Fri, 06 Oct 2017 04:46:45 GMT
Server: Redacted
Trackingid: NA_1acc0751-8f73-4a18-9386-aa124ea680c0
X-Cf-Requestid: 267ba7bf-8938-4fdf-62df-9ded56e44633
{"message":"ff8ee6fb-afef-4a4d-92b1-d6b216b58949 is already in the
room.","errors":[{"description":"ff8ee6fb-afef-4a4d-92b1-d6b216b58949 is
already in the room."}],"trackingId":"NA_1acc0751-8f73-4a18-9386-aa124ea680c0"}
```
