### ISSUE TITLE
Message posting with File URL isn't working....

### ISSUE THREAD

**Issue by brbester** [CiscoDevNet/ciscosparkapi#8]
Not sure if it is on my end, but when I pass a URL the script bombs.  Tried both as a string and a string in a list....

```
test_url="https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cisco_logo.svg/375px-Cisco_logo.svg.png"
Traceback (most recent call last):
  File "testapi.py", line 37, in <module>
    message = api.messages.create(room.id,None,None,None,None,test_url)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/api/messages.py", line 217, in create
    assert files is None or isinstance(files, list)
AssertionError
```

```
test_url=["https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cisco_logo.svg/375px-Cisco_logo.svg.png"]
Traceback (most recent call last):
  File "testapi.py", line 37, in <module>
    message = api.messages.create(room.id,None,None,None,None,test_url)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/api/messages.py", line 239, in create
    post_data[u'files'] = utf8(files)
  File "/usr/local/lib/python2.7/dist-packages/ciscosparkapi/helper.py", line 98, in utf8
    assert isinstance(string, basestring)
AssertionError
```

**Comment by cmlccie** [comment]
Brad, thank you for reporting this.  I have fixed the issue.  It was simply a matter of the 'files' parameter not being treated as a list as it should be.  It is fixed in v0.1.2, which has been posted to PyPI.
